#!/bin/bash


echo "---> Installing new content ..."
rsync -avP /tmp/src/ ./ --no-times --no-perms
if [ -f "/tmp/src/nginx/webportal-nginx.conf" ]; then
     echo "---> Applying custom Nginx config ..."
     cp -f /tmp/src/nginx/webportal-nginx.conf /etc/nginx/sites-available/webportal-nginx.conf
     chmod 664 /etc/nginx/sites-available/webportal-nginx.conf
fi

echo "---> Build SOLR Collections ..."
make clean-all && \
    make build-all && \
    ./build/bin/solr start -force && \
    sleep 20 && \
    make force-load-data || true

# Fix source directory permissions
fix-permissions ./