#!/bin/bash


echo "---> Installing new content ..."
rsync -aq /tmp/src/specify_exports/ ./specify_exports/
if [ -f "/tmp/src/nginx/webportal-nginx.conf" ]; then
     echo "---> Applying custom Nginx config ..."
     cp -f /tmp/src/nginx/webportal-nginx.conf /etc/nginx/sites-available/webportal-nginx.conf
     chmod 664 /etc/nginx/sites-available/webportal-nginx.conf
fi

echo "---> Extracting Catalogs ..."
for i in specify_exports/*.zip
do
  echo "--> Extracting $i ..."
  unzip -DD -qq -o -d build/col/catalog $i
done

echo "---> Build SOLR Collections ..."
make clean-all && \
    make build-all && \
    ./build/bin/solr start -force && \
    sleep 20 && \
    make load-data || true

# Fix source directory permissions
fix-permissions ./