#!/bin/bash

echo "---> Extracting Catalogs ..."
for i in specify_exports/%*.zip
do
  echo "--> Extracting $i ..."
  unzip -DD -qq -o -d build/col/$* $i
done
echo "---> Starting SOLR ..."
./build/bin/solr start -force
echo "---> Pausing for 20 seconds ..."
sleep 20
echo "---> Loading new content ..."
make load-data || true
echo "---> Starting nginx ..."
nginx -g 'daemon off;'